"""Consequential adapter mutations are claimed and reconciled before retry."""

from unittest.mock import MagicMock, patch

import pytest

from src.adapters.base import ReconciliationOutcome, ReconciliationResult
from src.core.exceptions import AdCPCapabilityNotSupportedError, AdCPServiceUnavailableError
from src.core.resolved_identity import ResolvedIdentity
from src.core.schemas import UpdateMediaBuySuccess
from src.services.downstream_reconciliation import execute_reconciled_media_buy_update
from tests.factories import PrincipalFactory


def _identity() -> ResolvedIdentity:
    return PrincipalFactory.make_identity(
        tenant_id="tenant-1",
        principal_id="principal-1",
        account_id="account-1",
        tenant={"tenant_id": "tenant-1"},
    )


def _call(adapter, work):
    return execute_reconciled_media_buy_update(
        adapter=adapter,
        identity=_identity(),
        idempotency_key="update-key-0001",
        operation_key="pkg-1:pause_package",
        media_buy_id="mb-1",
        action="pause_package",
        package_id="pkg-1",
        budget=None,
        response_decoder=UpdateMediaBuySuccess.model_validate,
        work=work,
    )


def test_fresh_claim_is_marked_invoked_then_applied() -> None:
    repo = MagicMock()
    repo.get.return_value = None
    repo.create.return_value = MagicMock(
        claim_id="claim-1",
        status="planned",
        request_hash="ignored",
        result_metadata=None,
    )
    # Match the canonical hash generated by the service.
    from src.core.idempotency_canonical import canonical_payload_hash

    repo.create.return_value.request_hash = canonical_payload_hash(
        {
            "media_buy_id": "mb-1",
            "action": "pause_package",
            "package_id": "pkg-1",
            "budget": None,
            "implementation_date": None,
        }
    )
    uow = MagicMock(downstream_mutation_claims=repo)
    uow.__enter__.return_value = uow
    adapter = MagicMock()
    result = UpdateMediaBuySuccess(media_buy_id="mb-1", affected_packages=[])
    work = MagicMock(return_value=result)

    with patch("src.services.downstream_reconciliation.IdempotencyUoW", return_value=uow):
        assert _call(adapter, work) is result

    assert repo.create.call_args.kwargs["provider"] == "MagicMock"
    assert [call.kwargs["status"] for call in repo.transition.call_args_list] == ["invoked", "applied"]


def test_unknown_prior_outcome_fails_closed_without_reinvoking() -> None:
    from src.core.idempotency_canonical import canonical_payload_hash

    repo = MagicMock()
    repo.get.return_value = MagicMock(
        claim_id="claim-1",
        status="invoked",
        request_hash=canonical_payload_hash(
            {
                "media_buy_id": "mb-1",
                "action": "pause_package",
                "package_id": "pkg-1",
                "budget": None,
                "implementation_date": None,
            }
        ),
        result_metadata=None,
    )
    uow = MagicMock(downstream_mutation_claims=repo)
    uow.__enter__.return_value = uow
    adapter = MagicMock(adapter_name="mock")
    adapter.reconcile_media_buy_update.return_value = ReconciliationResult(ReconciliationOutcome.UNKNOWN)
    work = MagicMock()

    with (
        patch("src.services.downstream_reconciliation.IdempotencyUoW", return_value=uow),
        pytest.raises(AdCPServiceUnavailableError, match="outcome is unknown"),
    ):
        _call(adapter, work)

    work.assert_not_called()
    repo.transition.assert_called_once_with("claim-1", status="unknown")


def test_existing_planned_claim_is_known_not_invoked_and_executes_once() -> None:
    from src.core.idempotency_canonical import canonical_payload_hash

    repo = MagicMock()
    repo.get.return_value = MagicMock(
        claim_id="claim-1",
        status="planned",
        request_hash=canonical_payload_hash(
            {
                "media_buy_id": "mb-1",
                "action": "pause_package",
                "package_id": "pkg-1",
                "budget": None,
                "implementation_date": None,
            }
        ),
        result_metadata=None,
    )
    uow = MagicMock(downstream_mutation_claims=repo)
    uow.__enter__.return_value = uow
    adapter = MagicMock(adapter_name="mock", supports_media_buy_update_reconciliation=True)
    expected = UpdateMediaBuySuccess(media_buy_id="mb-1", affected_packages=[])
    work = MagicMock(return_value=expected)

    with patch("src.services.downstream_reconciliation.IdempotencyUoW", return_value=uow):
        assert _call(adapter, work) is expected

    adapter.reconcile_media_buy_update.assert_not_called()
    work.assert_called_once_with()


def test_unsupported_adapter_is_rejected_before_claim_or_provider_invocation() -> None:
    adapter = MagicMock(adapter_name="xandr", supports_media_buy_update_reconciliation=False)
    work = MagicMock()

    with pytest.raises(AdCPCapabilityNotSupportedError, match="cannot safely reconcile"):
        _call(adapter, work)

    work.assert_not_called()
