"""The vendored schema tree must actually be what its pin claims.

``PINNED_SHA`` is a provenance claim about every file under
``tests/fixtures/adcp_schemas_pinned/``: three test modules read that tree as their
ground truth for AdCP schema shapes and the error-code vocabulary. A claim nothing
checks is a label, and it drifted exactly that way once — the pin was advanced to a
later release commit while 243 of 245 files stayed at the older one, so the tree
declared a fidelity it did not have.

These tests close both directions offline:

* bumping the pin without re-running the refresh fails, because the manifest is only
  regenerated by an actual refresh run;
* hand-editing any vendored schema fails, because every file's digest is pinned.

One hole remains and cannot be closed offline: regenerating the manifest from an
unchanged tree after bumping the pin would satisfy both checks. Only a fetch of the
upstream bytes can catch that, which is why the network-gated faithfulness check in
``tests/integration/`` exists.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest

from tests.fixtures.adcp_schemas_pinned import _manifest, _refresh

FIXTURE_DIR = Path(_refresh.__file__).parent


def test_refresh_pin_matches_manifest_pin() -> None:
    """The declared pin and the recorded pin agree.

    They can only diverge if someone edited ``PINNED_SHA`` without re-running the
    refresh — which is precisely the bump-without-re-vendor that made the tree
    misrepresent itself.
    """
    assert _refresh.PINNED_SHA == _manifest.PINNED_SHA, (
        f"_refresh.py pins {_refresh.PINNED_SHA} but the manifest records "
        f"{_manifest.PINNED_SHA}. Re-run tests/fixtures/adcp_schemas_pinned/_refresh.py "
        f"so the vendored bytes actually come from the pinned commit."
    )


def test_vendored_files_match_manifest_digests() -> None:
    """Every vendored file is byte-for-byte what was committed, and the set is complete.

    Catches a hand-edit anywhere in the tree — a spliced enum entry, a tweaked
    ``required``, a whole file added or removed — naming the offending path.
    """
    on_disk = {
        path.relative_to(FIXTURE_DIR).as_posix(): hashlib.sha256(path.read_bytes()).hexdigest()
        for path in sorted(FIXTURE_DIR.rglob("*.json"))
    }

    assert set(on_disk) == set(_manifest.FILE_DIGESTS), (
        "vendored file SET differs from the manifest — "
        f"added: {sorted(set(on_disk) - set(_manifest.FILE_DIGESTS))}, "
        f"removed: {sorted(set(_manifest.FILE_DIGESTS) - set(on_disk))}"
    )

    drifted = [rel for rel, digest in on_disk.items() if digest != _manifest.FILE_DIGESTS[rel]]
    assert drifted == [], (
        f"vendored schema content edited in place: {drifted}. Vendored files are a faithful "
        f"copy of upstream — change them by re-running _refresh.py against a new pin, or by "
        f"declaring the change in _refresh.SUPPLEMENT."
    )


def test_error_code_enum_is_base_plus_declared_supplement() -> None:
    """The vocabulary is exactly the base commit's, plus what the supplement declares.

    Exact set equality rather than a count: a count is satisfied by a swap (one code
    added, one removed) and by any ``enumMetadata`` edit that leaves ``enum`` untouched.
    """
    supplement = _manifest.SUPPLEMENT["enums/error-code.json"]
    added = set(supplement["codes_added"])  # type: ignore[arg-type]

    enum = set(json.loads((FIXTURE_DIR / "enums/error-code.json").read_text())["enum"])
    expected = set(_manifest.BASE_ERROR_CODES) | added

    assert enum == expected, (
        f"error-code vocabulary drifted — unexpected: {sorted(enum - expected)}, "
        f"missing: {sorted(expected - enum)}. Codes transplanted from a later upstream "
        f"source must be declared in _refresh.SUPPLEMENT, not spliced in silently."
    )


def test_supplement_is_fully_declared() -> None:
    """Everything the supplement claims to transplant is actually present, with a reason.

    Stops the declaration from rotting into a comment that no longer describes the tree.
    """
    for rel, meta in _refresh.SUPPLEMENT.items():
        schema = json.loads((FIXTURE_DIR / rel).read_text())
        enum = set(schema["enum"])

        for code in meta["codes_added"]:  # type: ignore[union-attr]
            assert code in enum, f"{rel} declares {code} as transplanted, but it is not in the file"
        for code in meta["entries_replaced"]:  # type: ignore[union-attr]
            assert code in enum, f"{rel} declares {code} as replaced, but it is not in the file"

        assert str(meta.get("reason", "")).strip(), f"{rel} supplement needs a reason — why was this transplanted?"
        assert len(str(meta.get("source_sha", ""))) == 40, f"{rel} supplement needs the full source commit sha"


@pytest.mark.parametrize("code", ["AUTH_MISSING", "AUTH_INVALID"])
def test_production_emitted_auth_codes_are_covered(code: str) -> None:
    """The codes production emits are in the vocabulary the guards grade against.

    This is why the supplement exists rather than a plain revert: the recovery-conformance
    guard resolves these against the fixture, so dropping them would fail the build even
    though the base commit predates the split.
    """
    enum = set(json.loads((FIXTURE_DIR / "enums/error-code.json").read_text())["enum"])
    assert code in enum
